# Generated by Django 5.0.3 on 2024-03-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'Услуги', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterField(
            model_name='services',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
