# Generated by Django 5.0.3 on 2024-03-04 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_services_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service_view',
            options={'verbose_name': 'Виды услуги', 'verbose_name_plural': 'Виды услуги'},
        ),
        migrations.AlterField(
            model_name='service_view',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='service_view',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_view', to='pages.services', verbose_name='Выберите услугу'),
        ),
    ]
