# Generated by Django 5.0.3 on 2024-03-04 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_service_view_options_alter_service_view_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Master_and_service_view',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_and_service_view', to='pages.master', verbose_name='Выберите мастера')),
                ('service_view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_and_service_view_1', to='pages.service_view', verbose_name='Выберите услугу')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
            },
        ),
    ]
