# Generated by Django 5.0.3 on 2024-03-07 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_services_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='master_and_service_view',
            options={'verbose_name': 'Услуги Мастера', 'verbose_name_plural': 'Услуги Мастера'},
        ),
    ]
