# Generated by Django 5.0.3 on 2024-03-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_feedback_options_alter_feedback_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['datetime'], 'verbose_name': 'Обратная связь', 'verbose_name_plural': 'Обратные связи'},
        ),
        migrations.AddField(
            model_name='service_view',
            name='currency',
            field=models.CharField(default=1, max_length=255, verbose_name='Валюта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service_view',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
