# Generated by Django 4.1.13 on 2024-03-08 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_alter_feedback_options_service_view_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('service', models.CharField(max_length=225)),
                ('master', models.CharField(max_length=225)),
                ('phonenumber', models.CharField(max_length=225)),
            ],
            options={
                'verbose_name': 'Записи',
            },
        ),
    ]
