# Generated by Django 4.1.13 on 2024-03-09 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_alter_records_services'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Applications',
        ),
        migrations.AlterModelOptions(
            name='records',
            options={'verbose_name': 'Записи', 'verbose_name_plural': 'Записи'},
        ),
        migrations.AddField(
            model_name='records',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
