# Generated by Django 5.0 on 2024-03-28 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_records_date_rec_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='records',
            name='date_rec',
        ),
        migrations.AddField(
            model_name='records',
            name='services_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services_user', to='pages.services'),
        ),
    ]
