# Generated by Django 5.0 on 2024-03-28 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_remove_records_date_rec_records_services_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='records',
            options={'ordering': ['date_rec_info'], 'verbose_name': 'Записи', 'verbose_name_plural': 'Записи'},
        ),
        migrations.AddField(
            model_name='records',
            name='date_rec',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
