# Generated by Django 5.0 on 2024-05-05 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_alter_records_options_records_date_rec'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование салона')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('rating', models.CharField(max_length=255, verbose_name='Рейтинг салона')),
            ],
            options={
                'verbose_name': 'Салон',
                'verbose_name_plural': 'Салон',
            },
        ),
    ]
