# Generated by Django 5.0 on 2024-05-05 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_salons'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Адресс филиала')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('rating', models.CharField(max_length=255, verbose_name='Рейтинг филиала')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salon', to='pages.salons', verbose_name='Салон')),
            ],
            options={
                'verbose_name': 'Салон',
                'verbose_name_plural': 'Салон',
            },
        ),
    ]
