# Generated by Django 5.0 on 2024-05-05 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_branch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': 'Филиалы', 'verbose_name_plural': 'Филиалы'},
        ),
    ]
