# Generated by Django 5.0 on 2024-05-05 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_alter_branch_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch', to='pages.salons', verbose_name='Салон'),
        ),
    ]
