# Generated by Django 5.0 on 2024-05-05 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_services_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch', to='pages.branch', verbose_name='Филиал'),
        ),
    ]
