# Generated by Django 5.0 on 2024-05-05 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_master_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер телефона'),
        ),
    ]
