# Generated by Django 5.0 on 2024-05-06 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0028_alter_services_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='rating',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Рейтинг услуги'),
        ),
    ]
