# Generated by Django 5.0 on 2024-05-06 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0029_alter_services_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
