# Generated by Django 5.0 on 2024-05-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0030_alter_records_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Адресс филиала')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('price', models.CharField(blank=True, max_length=255, null=True, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Заказ')),
                ('tapchan', models.CharField(max_length=255, verbose_name='Тапчан №')),
                ('food', models.CharField(max_length=255, verbose_name='Заказ из меню')),
                ('price', models.CharField(max_length=255, verbose_name='Сумма заказа')),
                ('person', models.CharField(max_length=255, verbose_name='Клиент')),
                ('number', models.CharField(max_length=255, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
            },
        ),
        migrations.CreateModel(
            name='Tapchan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Тапчан')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('price', models.CharField(max_length=255, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Тапчан',
                'verbose_name_plural': 'Тапчан',
            },
        ),
        migrations.RemoveField(
            model_name='branch',
            name='salon',
        ),
        migrations.RemoveField(
            model_name='services',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='master',
            name='branch',
        ),
        migrations.DeleteModel(
            name='FeedBack',
        ),
        migrations.RemoveField(
            model_name='master_and_service_view',
            name='master',
        ),
        migrations.RemoveField(
            model_name='master_and_service_view',
            name='service_view',
        ),
        migrations.RemoveField(
            model_name='records',
            name='services_info',
        ),
        migrations.RemoveField(
            model_name='records',
            name='user',
        ),
        migrations.RemoveField(
            model_name='service_view',
            name='service',
        ),
        migrations.DeleteModel(
            name='Salons',
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.DeleteModel(
            name='Master',
        ),
        migrations.DeleteModel(
            name='Master_and_service_view',
        ),
        migrations.DeleteModel(
            name='Records',
        ),
        migrations.DeleteModel(
            name='Service_View',
        ),
        migrations.DeleteModel(
            name='Services',
        ),
    ]
