# Generated by Django 5.0 on 2024-05-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0031_menu_order_tapchan_remove_branch_salon_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Брони', 'verbose_name_plural': 'Брони'},
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Наименование блюда'),
        ),
        migrations.AlterField(
            model_name='order',
            name='food',
            field=models.TextField(max_length=255, verbose_name='Заказ из меню'),
        ),
    ]
