# Generated by Django 5.0 on 2024-05-08 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0032_alter_order_options_alter_menu_name_alter_order_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_rec',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
