# Generated by Django 5.0 on 2024-05-08 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0033_order_date_rec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_rec',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
